# Generated by Django 5.0.7 on 2024-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit Money'), (2, 'Borrow Book'), (3, 'Return Book')], null=True),
        ),
    ]
