# Generated by Django 5.0.7 on 2024-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='return_book',
            field=models.BooleanField(default=False),
        ),
    ]
